# Generated by Django 6.0 on 2025-12-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='access_code',
        ),
        migrations.AddField(
            model_name='quiz',
            name='code',
            field=models.CharField(default='ABCD', help_text='Code players use to join', max_length=10),
        ),
    ]
